name: Update Waste Schedule

on:
  schedule:
    - cron: '0 1 * * *'  # Runs at 1:00 AM UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-schedule:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.27"
    
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
        
    - name: Install the project
      run: uv sync --all-extras --dev

      - name: Run tests
      run: uv run when.py 

    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update waste collection schedule" && git push)
